[package]
name = "day_{{day}}"
version = "0.1.0"
{% if author %}authors = ["{{author}}"]{% endif %}
edition = "{{rust_edition}}"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
