[package]
name = "day_{{day}}"
version = "0.1.0"
edition = "{{rust_edition}}"
{% if author %}authors = ["{{author}}"]{% endif %}

[lib]
doctest = false

[[bin]]
name = "day_{{day}}"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
